import Nav from '@/components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></Script>
      <body className={inter.className}>
        <Nav />
        <main className="flex min-h-screen flex-col items-center justify-between p-8 md:px-24">
          {children}
        </main>
        <footer className="text-gray-500 text-xs p-16 m-auto w-full text-center">© 2023 Ed Prince</footer>
      </body>
    </html>
  )
}
